# Server
server.port=8081

# Application name
spring.application.name=food-request-service

# Disable Config Server
spring.config.import=optional:configserver:
spring.cloud.config.enabled=false

# Disable Service Discovery
eureka.client.enabled=false

# Standalone H2 database
spring.datasource.url=jdbc:h2:mem:fooddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# gRPC server
grpc.server.port=9091

# Logging
logging.level.root=INFO