spring.application.name=food-service
server.port=8081
# --- gRPC server (food-service exposes FoodService here) ---
grpc.server.port=9091
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Springdoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.theme=monokai

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true